import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // shadcn/ui components are vendor code generated by the shadcn CLI.
  // We don't author them; new React lint rules trip their patterns.
  globalIgnores(['dist', 'src/components/ui/**']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // React 19 strict-mode rules below are downgraded to warnings so CI
      // can run on existing code. Each is real tech debt to clean up in a
      // follow-up sweep; lint output still surfaces them so we don't lose
      // signal. See chore/lint-cleanup follow-up.
      'react-hooks/purity': 'warn',                  // Math.random() in render (preview pages)
      'react-hooks/set-state-in-effect': 'warn',     // setState inside useEffect synchronously
      'react-refresh/only-export-components': 'warn', // files exporting both components and helpers
    },
  },
])
